name: app_analisi_cute
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.1+1 # Pacchetto base per la fotocamera
  camera_web: ^0.3.5 # Implementazione web della fotocamera
  path_provider: ^2.0.15
  model_viewer_plus: ^1.9.0
  http: ^1.2.2
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true